language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y pkg-config ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then git -C .. clone https://github.com/MediaArea/ZenLib.git ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then pushd ../ZenLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then git -C .. clone https://github.com/JeromeMartinez/MediaInfoLib.git --branch DVRescue ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then pushd ../MediaInfoLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then git -C .. clone https://github.com/MediaArea/ZenLib.git ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then pushd ../ZenLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then git -C .. clone https://github.com/JeromeMartinez/MediaInfoLib.git --branch DVRescue ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then pushd ../MediaInfoLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd ; fi

script: cd Project/GNU/CLI/ && sh autogen.sh && ./configure && make
