title: DVRescue
description: Procedures and tools that will support migrating data from DV tapes into digital files suitable for long-term preservation.
baseurl: 
url: http://mipops.github.io/dvrescue-documentation
collections: 
  sections:
    output: true
          